/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Logic.LoadFile;
import Logic.MemoryParser;
import Logic.State;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.Properties;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ksala
 */
public class Interfaz extends javax.swing.JFrame {

    public int kernel = 6;
    public int user = 14;
    public int memory = 20;
    public int disc = 40;
    public int virtual = 10 ;
    public int particion = 4;
    public String modo = "Particionamiento fijo";
    public int quantum;
    
    public MemoryParser m;
    
    int indiceProceso = 0;
    
    public PCBViewer pcb = new PCBViewer();
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.auto.setVisible(false);
        this.paso.setVisible(false);
        leerProperties();
        this.m = new MemoryParser(user, kernel, disc, virtual, modo, particion);
        this.ram.setText(this.m.formattingRam());
        this.memoria.setText(this.m.formattingDisc());
    }

    public final void leerProperties(){
        Properties properties = new Properties();
        
        try (FileInputStream input = new FileInputStream(System.getProperty("user.dir")+"\\config.properties")) {
            properties.load(input);
            
            this.kernel = Integer.parseInt(properties.getProperty("kernel"));
            this.user = Integer.parseInt(properties.getProperty("user"));
            this.memory = Integer.parseInt(properties.getProperty("memory"));
            this.disc = Integer.parseInt(properties.getProperty("disc"));
            this.virtual = Integer.parseInt(properties.getProperty("memoryVirtual"));
            this.particion = Integer.parseInt(properties.getProperty("PartitionSize"));
            this.modo = properties.getProperty("Type");
            this.quantum = Integer.parseInt(properties.getProperty("Quantum"));
            
        } catch (Exception e) {
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cargar = new javax.swing.JButton();
        reiniciar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        procesos = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        bcps = new javax.swing.JTable();
        verBCP = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ram = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        memoria = new javax.swing.JTextPane();
        execButton = new javax.swing.JButton();
        gantt = new javax.swing.JScrollPane();
        jLabel4 = new javax.swing.JLabel();
        algoritmo = new javax.swing.JComboBox<>();
        configuracion = new javax.swing.JButton();
        paso = new javax.swing.JButton();
        auto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cargar.setText("Cargar archivo");
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });

        reiniciar.setText("Reiniciar");
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setText("Procesos");

        jScrollPane1.setViewportView(procesos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
        );

        bcps.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BCP ID", "memDir", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(bcps);

        verBCP.setText("Seleccione un BCP para verlo");
        verBCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBCPActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setText("Memoria secundaria");

        jLabel3.setText("Memoria principal");

        jScrollPane3.setViewportView(ram);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane4.setViewportView(memoria);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(46, 46, 46))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        execButton.setText("Ejecutar");
        execButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                execButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Diagrama de Gantt");

        algoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "SRT", "SJF", "RR", "HRRN" }));
        algoritmo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                algoritmoItemStateChanged(evt);
            }
        });

        configuracion.setText("Configuración");
        configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configuracionActionPerformed(evt);
            }
        });

        paso.setText("paso a paso");
        paso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasoActionPerformed(evt);
            }
        });

        auto.setText("Auto");
        auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(gantt, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(verBCP, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(reiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(algoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(execButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paso, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(auto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(execButton)
                                .addComponent(algoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(paso)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(reiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(auto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(verBCP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(gantt, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public Logic.Process buscarProceso2(int i){
        Logic.Process actual = null;
        int x = 0;
        for(Logic.Process p: this.m.listaProcesos){
            if(p.id == i){
                actual = p;
                break;
            }
            x++;
        }
        return actual;
    }
    
    private void verBCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBCPActionPerformed
        mostrarPCB();
    }//GEN-LAST:event_verBCPActionPerformed

    public void mostrarPCB(){
        int selectedRow = bcps.getSelectedRow(); // Obtener el índice de la fila seleccionada

        if (selectedRow != -1) { // Verificar que haya una fila seleccionada
            int bcpId = (int) bcps.getValueAt(selectedRow, 0); // Obtener el valor en la columna 'BCP ID' (índice 0)
            System.out.println("BCP ID seleccionado: " + bcpId);
            this.pcb.update(buscarProceso2(bcpId));
            this.pcb.state.setText(bcps.getValueAt(selectedRow, 2).toString());
            if(pcb.isVisible()){
                pcb.repaint();
                pcb.setVisible(true);
            }
            else{
                this.pcb.setVisible(true);
            }
        } else {
            System.out.println("No se ha seleccionado ninguna fila.");
        }
    }
    
    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        reset();
    }//GEN-LAST:event_reiniciarActionPerformed

    public void agregarFila(int bcpId, int memDir, String estado) {
        DefaultTableModel model = (DefaultTableModel) bcps.getModel();
        model.addRow(new Object[]{bcpId, memDir, estado});
    }
    
    public void eliminarFilaPorId(int bcpId) {
        DefaultTableModel model = (DefaultTableModel) bcps.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            if ((int) model.getValueAt(i, 0) == bcpId) { // Verifica si el valor de BCP ID coincide
                model.removeRow(i); // Elimina la fila
                break; // Detiene el bucle después de eliminar
            }
        }
    }
    public void editarFilaPorId(int bcpId, String nuevoEstado) {
        DefaultTableModel model = (DefaultTableModel) bcps.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            if ((int) model.getValueAt(i, 0) == bcpId) { // Verifica si el valor de BCP ID coincide
                model.setValueAt(nuevoEstado, i, 2); // Actualiza la tercera columna con el nuevo estado
                break; // Detiene el bucle después de encontrar y editar la fila
            }
        }
    }

    public void limpiarTabla() {
        DefaultTableModel model = (DefaultTableModel) bcps.getModel();
        model.setRowCount(0); // Establece el número de filas en 0, eliminando todas las filas
    }


    public void reset(){
        this.setVisible(false);
        this.dispose();

        new Interfaz().setVisible(true);
    }
    
    private void execButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_execButtonActionPerformed
        if(this.m.listaProcesos.isEmpty()){
            return;
        }
        this.algoritmo.setEnabled(false);
        this.auto.setVisible(true);
        this.execButton.setEnabled(false);
        this.paso.setVisible(true);
        
        switch(this.algoritmo.getSelectedItem().toString()){
            case "FCFS" -> this.m.FCFS();
            case "SJF" -> this.m.SJF();
            case "SRT" -> this.m.SRT();
            case "RR" -> this.m.RoundRobin(this.quantum);
            default -> this.m.HRRN();
        }
        
        System.out.println(this.m.ejecucion.toString());
                //mostrarGantt();
    }//GEN-LAST:event_execButtonActionPerformed

    public Logic.Process buscarProceso(int i){
        Logic.Process actual = null;
        int x = 0;
        for(Logic.Process p: this.m.listaProcesos){
            if(p.id == i){
                actual = p;
                actual.ownPCB.setState(State.RUNNING);
                actual.rafaga++;
                break;
            }
            x++;
        }
        //m.listaProcesos.add(x, actual);
        return actual;
    }

    public void initTablaProcesos(){
        String res = "";
        for(Logic.Process x: m.listaProcesos){
            res+= "Proceso "+ x.id+"->"+x.ownPCB.getState().toString()+"\n";
        }
        this.procesos.setText(res);
    }
    
    public void mostrarGantt() {
        Gantt ganttChartPanel = new Gantt(this.m);

        gantt.setViewportView(ganttChartPanel);
        gantt.revalidate(); // Actualiza el JScrollPane
        gantt.repaint(); // Redibuja el JScrollPane para mostrar el contenido
    }
    
    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        LoadFile.call().limpiar();
        LoadFile.call().openFiles();
        
        ArrayList<ArrayList<String>> codigos = LoadFile.call().codigos;
        ArrayList<Logic.Process> p = LoadFile.call().procesos;
        
        for(int i=0; i<codigos.size(); i++){
            Logic.Process proceso = this.m.asignarProceso(p.get(i), codigos.get(i));
            agregarFila(proceso.ownPCB.id, proceso.ownPCB.getPC(), proceso.ownPCB.getState().toString());
        }
        
        ram.setText(m.formattingRam());
        memoria.setText(m.formattingDisc());
        this.initTablaProcesos();
    }//GEN-LAST:event_cargarActionPerformed

    private void algoritmoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_algoritmoItemStateChanged
        System.out.println("algoritmo seleccionado: "+algoritmo.getSelectedItem().toString());
    }//GEN-LAST:event_algoritmoItemStateChanged

    private void configuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configuracionActionPerformed
        Config co = new Config(this);
        co.setCurrentValues(kernel, user, disc, virtual, particion, modo, quantum);
        co.seteo();
        co.setVisible(true);
    }//GEN-LAST:event_configuracionActionPerformed

    private void autoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoActionPerformed

    private void pasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasoActionPerformed
        String actual;
        
        if(pcb.isVisible()){
            pcb.repaint();
            pcb.setVisible(true);
        }
        if(m.listaProcesos.isEmpty()){
            return;
        }
        try{
            actual = m.ejecucion.get(indiceProceso);
        }catch(Exception e){
            this.execButton.setEnabled(true);
            this.algoritmo.setEnabled(true);
            this.auto.setVisible(false);
            this.paso.setVisible(false);
            for(Logic.Process x: m.listaProcesos){
                if(x.ownPCB.getState().toString().equals("RUNNING")){x.ownPCB.setState(State.FINISHED);}
                this.editarFilaPorId(x.id, x.ownPCB.getState().toString());
                this.initTablaProcesos();
                
            }
            m.limpiar();
            System.out.println("limpio");
            this.ram.setText(m.formattingRam());
            this.limpiarTabla();
            this.m.listaProcesos.clear();
            this.m.ejecucion.clear();
            this.indiceProceso = 0;
            return;
        }
        Logic.Process proceso;
        try{
            proceso = this.buscarProceso(Integer.parseInt(actual));
        }
        catch(Exception e){
            return;
        }
        for(Logic.Process x: m.listaProcesos){
            this.editarFilaPorId(x.id, x.ownPCB.getState().toString());
            if(x.ownPCB.getState().toString().equals("RUNNING")){x.ownPCB.setPC(x.ownPCB.getPC()+1);}
            this.initTablaProcesos();
        }
        
        indiceProceso++;
        if(proceso.rafaga >= proceso.getFileContent().size()){
            m.listaProcesos.get(m.listaProcesos.indexOf(proceso)).ownPCB.setState(State.FINISHED);
            
        }
        else if(indiceProceso>=m.ejecucion.size()){
            return;
        }
        else{
            m.listaProcesos.get(m.listaProcesos.indexOf(proceso)).ownPCB.setState(State.READY);
        }
        
        
    }//GEN-LAST:event_pasoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> algoritmo;
    private javax.swing.JButton auto;
    private javax.swing.JTable bcps;
    private javax.swing.JButton cargar;
    private javax.swing.JButton configuracion;
    private javax.swing.JButton execButton;
    private javax.swing.JScrollPane gantt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTextPane memoria;
    private javax.swing.JButton paso;
    private javax.swing.JTextPane procesos;
    public javax.swing.JTextPane ram;
    private javax.swing.JButton reiniciar;
    private javax.swing.JButton verBCP;
    // End of variables declaration//GEN-END:variables
}
