/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pkg1testfuntions;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Innovation Computers
 */
public class GanttChartPanel extends javax.swing.JPanel {

    private CPU cpu;
    private int timeUnitWidth = 50; // Ancho de cada unidad de tiempo
    private int processHeight = 30; // Altura de cada proceso
    private int currentStep = 0; // Paso actual para mostrar la ejecución paso a paso

    public GanttChartPanel(CPU cpu) {
        this.cpu = cpu;
        setPreferredSize(new Dimension(800, cpu.listaProcesos.size() * processHeight + 50));
        
        JButton stepButton = new JButton("Step");
        stepButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (currentStep < cpu.ejecucion.size()) {
                    currentStep++;
                    repaint();
                }
            }
        });
        this.add(stepButton);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int tiempoTotal = cpu.ejecucion.size();
        
        // Dibujar el encabezado de tiempo
        g.drawString("Tiempo", 10, 20);
        for (int i = 0; i < tiempoTotal; i++) {
            int x = 70 + i * timeUnitWidth;
            g.drawString("" + (i + 1), x, 20);
        }

        // Dibujar los procesos
        for (int i = 0; i < cpu.listaProcesos.size(); i++) {
            proceso p = cpu.listaProcesos.get(i);
            g.drawString(p.nombreProceso, 10, (i + 2) * processHeight);
        }

        // Dibujar la ejecución de cada proceso hasta el paso actual
        for (int tiempo = 0; tiempo < currentStep; tiempo++) {
            String procesoNombre = cpu.ejecucion.get(tiempo);
            for (int i = 0; i < cpu.listaProcesos.size(); i++) {
                if (cpu.listaProcesos.get(i).nombreProceso.equals(procesoNombre)) {
                    int x = 70 + tiempo * timeUnitWidth;
                    int y = (i + 1) * processHeight;
                    g.setColor(Color.GREEN);
                    g.fillRect(x, y + 10, timeUnitWidth, processHeight - 10);
                    g.setColor(Color.BLACK);
                    g.drawRect(x, y + 10, timeUnitWidth, processHeight - 10);
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
